create table if not exists public.demandas_teste (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    empresa text not null,
    processo text not null,
    descricao text not null default '',
    prioridade text not null default 'Normal'
        check (prioridade in ('Baixa', 'Normal', 'Alta', 'Urgente')),
    status text not null default 'Pendente'
        check (status in ('Pendente', 'Em andamento', 'Concluída'))
);

alter table public.demandas_teste enable row level security;

drop policy if exists "demo_select" on public.demandas_teste;
create policy "demo_select"
on public.demandas_teste for select
to anon
using (true);

drop policy if exists "demo_insert" on public.demandas_teste;
create policy "demo_insert"
on public.demandas_teste for insert
to anon
with check (true);

drop policy if exists "demo_update" on public.demandas_teste;
create policy "demo_update"
on public.demandas_teste for update
to anon
using (true)
with check (true);

